### ISSUE TITLE
Marmotta plugin shouldn't POST resource.

### ISSUE THREAD

**Issue by tpendragon** [ActiveTriples/linked-data-fragments#21]
I think we can just delete https://github.com/ActiveTriples/linked-data-fragments/blob/master/lib/linked_data_fragments/marmotta.rb#L11, but I wasn't sure if there was some reason it got added. @scande3?

**Comment by scande3** [comment]
I can't say I'm exactly sure what the "post" function does - I think I might have thought that was how your Marmotta gem cached the response? If that is incorrect, then yes, it can be removed.
